//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ShiftId { get; set; }
        public int DayOfTheWeek { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int RoleRequired { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
